### ISSUE TITLE
The project build failed because it could not download node.js

### ISSUE THREAD

**Issue by ralf0131** [alibaba/cloud-native-app-initializer#37]
I am on a Mac M1 laptop and when I am trying to build the project if failed with the following error message.

```
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for cloud-native-app-initializer 0.8:
[INFO]
[INFO] cloud-native-app-initializer ....................... SUCCESS [  0.003 s]
[INFO] initializer-page ................................... FAILURE [  2.818 s]
[INFO] initializer-generator .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.902 s
[INFO] Finished at: 2023-01-10T14:28:59+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-yarn (install node and yarn) on project initializer-page: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :initializer-page
```

**Comment by ralf0131** [comment]
After some googling, I figured it out it may related to https://github.com/eirslett/frontend-maven-plugin/issues/952.  Upgrading the version of frontend-maven-plugin to 1.11.0 works for me.

**Comment by ralf0131** [comment]
After fixing the issue above, I have encountered another issue: 

```
[INFO] gyp verb `which` failed   code: 'ENOENT' }
[INFO] gyp ERR! configure error
[INFO] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[INFO] gyp ERR! stack     at PythonFinder.failNoPython (~/work/cloud-native-app-initializer/initializer-page/node_modules/node-gyp/lib/configure.js:484:19)
[INFO] gyp ERR! stack     at PythonFinder.<anonymous> (~/work/cloud-native-app-initializer/initializer-page/node_modules/node-gyp/lib/configure.js:406:16)
[INFO] gyp ERR! stack     at F (~/work/cloud-native-app-initializer/initializer-page/node_modules/which/which.js:68:16)
[INFO] gyp ERR! stack     at E (~/work/cloud-native-app-initializer/initializer-page/node_modules/which/which.js:80:29)
[INFO] gyp ERR! stack     at ~/work/cloud-native-app-initializer/initializer-page/node_modules/which/which.js:89:16
[INFO] gyp ERR! stack     at ~/work/cloud-native-app-initializer/initializer-page/node_modules/isexe/index.js:42:5
[INFO] gyp ERR! stack     at ~/work/cloud-native-app-initializer/initializer-page/node_modules/isexe/mode.js:8:5
[INFO] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
[INFO] gyp ERR! System Darwin 21.6.0
[INFO] gyp ERR! command "~/work/cloud-native-app-initializer/initializer-page/node/node" "~/work/cloud-native-app-initializer/initializer-page/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[INFO] gyp ERR! cwd ~/work/cloud-native-app-initializer/initializer-page/node_modules/node-sass
[INFO] gyp ERR! node -v v10.15.3
[INFO] gyp ERR! node-gyp -v v3.8.0
[INFO] gyp ERR! not ok
[INFO] Build failed with error code: 1
```

It looks like node requires python.  Therefore python is another dependency for the project. After installing python I got it fixed.
